name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        working-directory: ./Frontend
        run: npm install

      - name: Run frontend lint
        working-directory: ./Frontend
        run: npm run lint

      - name: Build frontend
        working-directory: ./Frontend
        run: npm run build

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for backend
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install backend dependencies
        working-directory: ./Backend
        run: npm install

      - name: Run backend lint
        working-directory: ./Backend
        run: npm run lint

      - name: Build backend
        working-directory: ./Backend
        run: npm run build
